## Data Cleaning

In [1]:
import pandas as pd
import numpy as np

## Importing raw data

In [2]:
raw_matches = pd.read_csv('matches.csv')

In [3]:
raw_deliveries = pd.read_csv('deliveries.csv')

## Creating a copy of raw data

In [4]:
matches = raw_matches.copy()
deliveries = raw_deliveries.copy()

In [5]:
matches.shape, deliveries.shape

((756, 18), (179078, 21))

## Cleaning Matches

In [6]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(4), object(14)
memory usage: 106.4+ KB

## Checking null values and replacing them with appropriate values

In [7]:
matches.isnull().sum()

id                   0
Season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [8]:
matches['winner'] = matches['winner'].fillna('No Result')

In [9]:
matches['city'] = matches['city'].fillna('Unknown')

In [10]:
matches['player_of_match'] = matches['player_of_match'].fillna('No Result')

In [11]:
matches['umpire1'] = matches['umpire1'].fillna("Unknown")
matches['umpire2'] = matches['umpire2'].fillna("Unknown")
matches['umpire3'] = matches['umpire3'].fillna("Unknown")

In [12]:
matches.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Unknown
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,Unknown
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,Unknown
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,Unknown
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,Unknown,Unknown,Unknown

## Giving appropriate datatypes to values of columns

In [13]:
cols = ['city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'result', 'winner', 'player_of_match', 'venue', 'umpire1', 'umpire2', 'umpire3']

matches[cols] = matches[cols].astype(str)

In [14]:
matches['date'] = pd.to_datetime(
    matches['date'],
    format='%d-%m-%Y',
    errors='coerce'
)

In [15]:
matches['date'].isnull().sum()

np.int64(0)

## Standardising Data

In [51]:
team_map = {
    "Mumbai Indians": "MI",
    "Chennai Super Kings": "CSK",
    "Royal Challengers Bangalore": "RCB",
    "Delhi Daredevils": "DC",
    "Delhi Capitals": "DC",
    "Kings XI Punjab": "PBKS",
    "Punjab Kings": "PBKS",
    "Sunrisers Hyderabad": "SRH",
    "Kolkata Knight Riders": "KKR",
    "Rajasthan Royals": "RR",
    "Rising Pune Supergiants": "RPS",
    "Pune Warriors": "RPS",
    "Gujarat Lions": "GL"
}

for col in ['team1', 'team2', 'winner', 'toss_winner']:
    matches[col] = matches[col].replace(team_map)

In [17]:
team_map = { 
    "Rising Pune Supergiant": "RPS",
    "Deccan Chargers": "SRH",
    "Kochi Tuskers Kerala": "KTK",
}

for col in ['team1', 'team2', 'winner', 'toss_winner']:
    matches[col] = matches[col].replace(team_map)

In [18]:
matches.shape

(756, 18)

In [19]:
matches = matches[matches['team1'] != matches['team2']]

In [20]:
matches['result_type'] = np.where(
    matches['win_by_runs'] > 0, 
    "Won by runs",
    np.where(matches['win_by_wickets'] > 0, "Won by wickets", "No Result")
)

## Checking duplicate values

In [21]:
matches.duplicated().sum()

np.int64(0)

## Cleaning deliveries

In [22]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [23]:
deliveries['total_runs'].unique()

array([ 0,  4,  2,  1,  6,  3,  5,  7, 10,  8])

## Checking null values and replacing them with appropriate values

In [24]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [25]:
deliveries.fillna({
    'dismissal_kind': "Not Out",
    'player_dismissed': "None",
    'fielder': "None"
}, inplace=True)

## Standardising Data

In [54]:
for col in ['batting_team', 'bowling_team']:
    deliveries[col] = deliveries[col].replace(team_map)

In [27]:
deliveries['batsman'] = deliveries['batsman'].str.strip()
deliveries['bowler'] = deliveries['bowler'].str.strip()

## Removing duplicate values

In [28]:
deliveries.duplicated().sum()

np.int64(23)

In [29]:
deliveries.drop_duplicates(inplace=True)

## Merging Dataframes

In [30]:
ipl = deliveries.merge(
    matches,
    left_on='match_id',
    right_on='id',
    how='left'
)

In [31]:
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,result_type
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,SRH,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Unknown,Won by runs
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,SRH,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Unknown,Won by runs
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,SRH,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Unknown,Won by runs
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,SRH,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Unknown,Won by runs
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,SRH,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Unknown,Won by runs

In [32]:
ipl.shape

(179055, 40)

## Post merge data cleaning

In [33]:
ipl.duplicated().sum()

np.int64(0)

In [43]:
ipl.drop(['id'], axis=1, inplace=True)

In [ ]:
ipl.drop(['team1', 'team2'], axis=1, inplace=True)

## Creating advanced features

In [74]:
ipl['is_ball'] = np.where(
    (ipl['wide_runs'] > 0) | (ipl['noball_runs'] > 0),
    0,
    1
)

In [78]:
ipl['phase'] = pd.cut(
    ipl['over'],
    bins=[0, 6, 15, 20],
    labels=['Powerplay', 'Middle', 'Death']
)

In [82]:
ipl['is_boundary'] = ipl['batsman_runs'].apply(lambda x: 1 if x in [4,6] else 0)

In [84]:
ipl.shape, matches.shape, deliveries.shape

((179055, 40), (756, 19), (179055, 21))

In [88]:
ipl['strike_rate'] = (ipl['batsman_runs'] / ipl['is_ball']) * 100

In [96]:
ipl['strike_rate'] = ipl['strike_rate'].fillna(0)

## Cleaned data into csv file

In [99]:
matches.to_csv("matches_cleaned.csv", index=False)
deliveries.to_csv("deliveries_cleaned.csv", index=False)
ipl.to_csv("ipl_cleaned.csv", index=False)

In [100]:
ipl.shape

(179055, 41)